### ISSUE TITLE
Consider defcustom instead of defvar

### ISSUE THREAD

**Issue by nikclayton** [dangom/write-as.el#1]
https://github.com/dangom/write-as.el/blob/48f4cf99388b6552a31ebb5e84da2669dbd37272/write-as.el#L50

Hi,

Instead of using `defvar` in a few places in the code, have you considered using `defcustom`? This would allow people to use the `customize` feature to manage changes to these variables.

There's more info at https://www.gnu.org/software/emacs/manual/html_node/eintr/defcustom.html.

**Comment by dangom** [comment]
Done! Thanks, again!
