### ISSUE TITLE
Use -- in internal function names

### ISSUE THREAD

**Issue by nikclayton** [dangom/write-as.el#2]
https://github.com/dangom/write-as.el/blob/48f4cf99388b6552a31ebb5e84da2669dbd37272/write-as.el#L67

Where you have 'internal' functions (functions that are not intended to be called by other packages) the convention is to have two hyphens after the package identifier, to mark them as being internal.

```
(defun write-as--get-orgmode-keyword (key) ... )
```

See the second bullet of https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html for more.

Hope that helps.

**Comment by dangom** [comment]
Thanks for taking your time to look at the code and make suggestions. I've renamed internal functions to follow the convention.
